### ISSUE TITLE
On save template returns '1'

### ISSUE THREAD

**Issue by hatzipanis** [madebyshape/comments-rating#1]
Please see this issue engram-design/Comments#57. Interestingly none of template code worked for me either.

Any thoughts would be most appreciated!

**Comment by madebyshape** [comment]
Dang - Will have a look in to this later on today. Do you have an example of this anywhere (Dev server or something?)

**Comment by hatzipanis** [comment]
Sorry for the slow response but thank you for looking into this!

I've reenabled the plugin but without implementing any of your code and the issue persists. Can I have an email to send you the dev site? It's a client site that has not gone live yet.

**Comment by madebyshape** [comment]
Yeah - Ping it over to jason@madebyshape.co.uk

**Comment by bymayo** [comment]
Sorry to chase this so late on - But did you resolve this issue? I couldn't replicate the problem.

If you fire me a link to see the error I'd be happy to look in to it.
