### ISSUE TITLE
Plugin version is incorrect

### ISSUE THREAD

**Issue by khalwat** [madebyshape/comments-rating#2]
The plugin `version` (and potentially the `schemaVersion`) is incorrect in the `CommentsRatingPlugin.php` file:

https://github.com/madebyshape/comments-rating/blob/master/commentsrating/CommentsRatingPlugin.php

The `releases.json` has it listed as `1.0.2` but the plugin itself thinks it's still 1.0.1.

This causes it to always think it needs to be updated in the AdminCP.

**Comment by bymayo** [comment]
Whoops - My mistake! Just fixed it :)
